collections:
  authors:
    output: true

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
    values:
      layout: "default"

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-environment-variables

# variables
form_key: {{ site.env.STATICFORMS_KEY }}

name: "Site Name"